trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"

parameters:
- name: Environment
  type: string
  default: TEST
  values:
    - TEST

variables:
- group: anfisa-frontend-${{ parameters.Environment }}

jobs:

  - job: "FrontendDockerBuild"
    displayName: "Frontend docker build"

    steps:
      - checkout: self
        clean: true


      - task: Bash@3
        displayName: 'Update build number'
        inputs:
          targetType: inline
          script: |
            npmVersionString=$(node -p "require('./package.json').version")
            echo "##vso[build.updatebuildnumber]${npmVersionString}.$(Build.BuildId)"
            echo $(Build.SourceBranchName)

      - task: Docker@2
        displayName: 'Docker build and push'
        inputs:
          containerRegistry: $(azContainerRegistry)
          repository: $(azRepository)
          Dockerfile: Dockerfile
          buildContext: .
          tags: $(Build.BuildNumber)
          addPipelineData: false
          addBaseImageData: false

      - task: PublishPipelineArtifact@1
        displayName: 'Publish helm as artifact'
        inputs:
          path: helm
          artifactName: helm
