resources:
  repositories:
    - repository: Helm
      type: git
      name: Forome/helm

trigger:
  batch: true
  branches:
   include:
     - develop
  tags:
    include:
      - v*
  paths:
    exclude:
      - /*
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
- group: anfisa-frontend-BUILD

jobs:

  - job: "FrontendDockerBuild"
    displayName: "Frontend docker build"

    steps:
      - checkout: self
        clean: true

      - task: Bash@3
        displayName: 'Update build number'
        inputs:
          workingDirectory: 'Anfisa-React-Client'
          targetType: inline
          script: |
            npmVersionString=$(node -p "require('./package.json').version")
            echo "##vso[build.updatebuildnumber]${npmVersionString}.$(Build.BuildId)"
            echo $(Build.SourceBranchName)

      - task: Docker@2
        displayName: 'Docker build and push'
        inputs:
          containerRegistry: $(azContainerRegistry)
          repository: $(azRepository)
          Dockerfile: Anfisa-React-Client/Dockerfile
          buildContext: Anfisa-React-Client
          tags: $(Build.BuildNumber)
          addPipelineData: false
          addBaseImageData: false

      - checkout: Helm

      - task: PublishPipelineArtifact@1
        displayName: 'Publish helm as artifact'
        inputs:
          path: helm/anfisa-front
          artifactName: helm
