trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"

parameters:
- name: Environment
  type: string
  default: TEST
  values:
    - TEST

variables:
- group: anfisa-react-client-${{ parameters.Environment }}

jobs:

  - job: "AnfisaReactClient"
    displayName: "Anfisa React Client"

    steps:
      - checkout: self
        clean: true


      - task: Bash@3
        displayName: 'set build number'
        inputs:
          targetType: inline
          script: |
            npmVersionString=$(node -p "require('./package.json').version")
            echo "##vso[build.updatebuildnumber]${npmVersionString}.$(Build.BuildId)"
            echo $(Build.SourceBranchName)

      - task: Docker@2
        displayName: 'buildAndPush'
        inputs:
          containerRegistry: $(azp_container_registry)
          repository: $(azp_repository)
          Dockerfile: ./Dockerfile
          buildContext: .
          tags: $(Build.BuildNumber)
          addPipelineData: false
          addBaseImageData: false

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          path: helm
          artifactName: helm
