trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"

parameters:
- name: Environment
  type: string
  default: DEBUG
  values:
    - DEBUG
    - QA
    - PORT

variables:
- group: AnfisaFront-${{ parameters.Environment }}

jobs:

  - job: AnfisaFront
    displayName: "Anfisa Front"

    steps:
      - checkout: self
        clean: true


      - task: Bash@3
        displayName: 'set build number'
        inputs:
          targetType: inline
          script: |
            npmVersionString=$(node -p "require('./package.json').version")
            echo "##vso[build.updatebuildnumber]${npmVersionString}.$(Build.BuildId)"
            echo $(Build.SourceBranchName)
            sed -i 's/develop/$(Build.SourceBranchName)/g' ./Dockerfile

      - task: Docker@2
        displayName: 'buildAndPush'
        inputs:
          containerRegistry: $(azp_container_registry)
          repository: $(azp_repository)
          Dockerfile: ./Dockerfile
          buildContext: .
          tags: $(Build.BuildNumber)
          addPipelineData: false
          addBaseImageData: false

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          path: .anfisafront-chart
          artifactName: AnfisaFront-Chart
