trigger:
- none

pool:
  vmImage: ubuntu-20.04

variables:
# - group: "ibm-cloud"
- group: "demo-frontend"

steps:

- task: Bash@3
  displayName: 'env-config'
  inputs:
    targetType: 'inline'
    script: |
      cat <<EOF > public/env-config.js
      window._env_ = {
        REACT_APP_URL_BACKEND: '$(REACT_APP_URL_BACKEND)'
      }
      EOF
      cat public/env-config.js