version: "3.9"

x-aliases:
  - &common_parameters
    networks:
    - anfisa

networks:
  anfisa:
    driver: bridge
    name: anfisa
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  anfisa-frontend:
    <<: *common_parameters
    container_name: anfisa-react-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - docker/.env
    restart: always
