version: "3.9"

x-aliases:
  - &common_parameters
    networks:
    - anfisa

networks:
  anfisa:
    driver: bridge
    name: anfisa
    ipam:
      config:
        - subnet:  172.23.0.0/16

services:
  anfisa-react-client:
    <<: *common_parameters
    container_name: anfisa-react-client
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker/.env
    ports:
      - "3000:80"
    restart: always