export const DASHBOARD_LAYOUT_COLS = 4
export const DASHBOARD_LAYOUT_ROW_HEIGHT = 36
export const DASHBOARD_LAYOUT_HORIZONTAL_SPACING = 8
export const DASHBOARD_LAYOUT_VERTICAL_SPACING = 16

export const DASHBOARD_ROW_OFFSET_HEIGHT =
  DASHBOARD_LAYOUT_ROW_HEIGHT + DASHBOARD_LAYOUT_HORIZONTAL_SPACING

export const DASHBOARD_COLS_OFFSET_HEIGHT =
  DASHBOARD_LAYOUT_COLS + DASHBOARD_LAYOUT_HORIZONTAL_SPACING

export const HIDDEN_RESIZE_HEIGHT = 20

export const DASHBOARD_LAYOUT_MARGIN: [number, number] = [
  DASHBOARD_LAYOUT_VERTICAL_SPACING,
  DASHBOARD_LAYOUT_HORIZONTAL_SPACING,
]
export const DASHBOARD_LAYOUT_CONTAINER_PADDING: [number, number] = [16, 16]

export const MAX_SUB_TAB_ROWS_AMOUNT = 40

export const DASHBOARD_LAYOUT_VERTICAL_MARGIN_CF = 0.15
