export const DecisionTreesMenuDataCy = {
  selectDecisionTree: 'select-decision-tree',
  applyFilter: 'apply-filter',
  decisionActions: 'actions',
  loadDecision: 'load',
  selectDropdownElem: 'dropdown-element',
  saveDataset: 'save-dataset',
  datasetNameInput: 'dataset-name-input',
  addNewDataset: 'Add dataset',
  cancelAddNewDataset: 'cancel-adding-dataset',
  textEditor: 'text-editor',
  createNew: 'create-new',
  applyNewTree: 'apply-new-dtree',
  newDecisionTreeNameInput: 'input[placeholder="Decision Tree name"]',
}
