# Default values

# ------------------------------------------------------------------------------
# Anfisa-ingress:
# ------------------------------------------------------------------------------
ingress:
  host: __anfisaFrontIngressHost__
  #oc get secrets -n openshift-ingress - view secrets with TLC-certificates

# ------------------------------------------------------------------------------
# anfisa_front:
# ------------------------------------------------------------------------------ 
anfisa_front:
  name: __anfisaFrontName__
  registry: __azdevops_agent_registry__:__Build.BuildNumber__
  branch: __anfisaFrontBranch__
  url_backend: https://__anfisaFrontIngressHost__/app

secret_token:
  name: registry
  azp_token: __azp_token__
