kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.anfisa_front.name }}
  labels:
    app: {{ .Values.anfisa_front.name }}
spec:
  selector:                
    matchLabels:     
      app: {{ .Values.anfisa_front.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.anfisa_front.name }}
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
      - name: {{ .Values.anfisa_front.name }}
        image: {{ .Values.anfisa_front.registry }}
        env:
        - name: BACKEND
          value: http://anfisa-backend:80
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/nginx/html/anfisa/env-config.js
            subPath: env-config.js
      serviceAccount: default
      imagePullSecrets:
      - name: registry
      volumes:
        - name: config-volume
          configMap:
            name: front-config
            defaultMode: 0666
      restartPolicy: Always
