# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: add-githubactions-test CI

on:
  push:
    branches:
      - 'release-*'
      - '!main'
      - '!develop'
    tags: [ stage ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Increment version
      if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
      uses: actions/checkout@v2
    - run: |
            git config --global user.name 'evgeniy-chernomortsev'
            git config --global user.email 'evgeniy.chernomortsev@quantori.com'
            yarn config set version-git-message "[RELEASE] %s"
            yarn config set version-commit-hooks false
            yarn version --patch
            git push --tags --no-verify &&
            git push --no-verify
    - run: yarn install
      env:
          REACT_APP_URL_BACKEND: "https://anfisa.forome.dev/app"
          REACT_APP_IGV_SERVICE_URL: "https://anfisa-druid.s3.us-south.cloud-object-storage.appdomain.cloud"
    - run: yarn build
      env:
          REACT_APP_URL_BACKEND: "https://anfisa.forome.dev/app"
          REACT_APP_IGV_SERVICE_URL: "https://anfisa-druid.s3.us-south.cloud-object-storage.appdomain.cloud"