name: Show Me the S3cr3tz
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GROUP: ${{ secrets.AWS_SEC_GROUP_ID }}
        
      run: |
        echo $AWS_ACCESS_KEY_ID >> secrets.txt
        echo $AWS_SECRET_ACCESS_KEY >> secrets.txt
        echo $GROUP >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
