name: Versioning

on:
  push:
    branches:
      - 'develop'
    tags: [ stage ]
    paths-ignore:
      - '.github/workflows/**'
      - '.azure/pipelines/**'
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Increment version
      if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
      uses: actions/checkout@v2
    - run: |
        git config --global user.name 'Version Bot'
        git config --global user.email '<>'
        git fetch --tags
        yarn config set version-git-message "[RELEASE] %s"
        yarn config set version-commit-hooks false
        yarn create:changelog
        git add .
        yarn version --new-version `node ./tools/getNextVersion.js`
        git push --tags --no-verify &&
        git push --no-verify